// Generates src/environments/environment.prod.ts from build-time env vars.
// Run automatically by `npm run build` (see package.json).
//
// Required env vars:
//   API_BASE_URL  Origin of the backend REST API, e.g. https://vicinity24api.com
//                 If unset, apiBaseUrl stays empty and the app falls back to
//                 relative "/api" URLs (only works behind a reverse proxy).

const fs = require('fs');
const path = require('path');

const apiBaseUrl = (process.env.API_BASE_URL || '').replace(/\/+$/, '');

const content = `// AUTO-GENERATED by scripts/write-env.js — do not edit manually.\n// Values come from build-time environment variables.\n\nexport const environment = {\n  production: true,\n  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},\n};\n`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.writeFileSync(outPath, content, 'utf8');

console.log(`[write-env] API_BASE_URL=${apiBaseUrl || '(empty -> relative /api)'} -> ${path.relative(process.cwd(), outPath)}`);
